name: Pipeline

on:
  push:
    branches:
      - dashboard

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: 🛒 Checkout code
        uses: actions/checkout@v2

      - name: 📦 Tar files
        run: tar -cvf source-${{ github.sha }}.tar .

      - name: 📬 Caching
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
            ${{ github.workspace }}/web/.next/cache
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}

      - name: 🔧 Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: 🔧 Configure Amplify
        uses: ambientlight/amplify-cli-action@0.2.1
        with:
          amplify_command: configure
          amplify_env: dev
          amplify_cli_version: "4.41.2"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1

      - name: 🔧 Set up JDK for dynamodb-local
        uses: actions/setup-java@v1
        with:
          java-version: 13

      - name: 🧰 Install Serverless Framework
        run: npm install -g serverless

      - name: 🔧 Serverless Authentication
        run: sls config credentials --provider aws --key ${{secrets.AWS_ACCESS_KEY_ID}} --secret ${{secrets.AWS_SECRET_ACCESS_KEY}}

      - name: 🧰 Install web dependencies
        run: npm --prefix=web install
      - name: 🧰 Install api dependencies
        run: npm --prefix=api install

      - name: 🧹 Run web lint
        run: npm --prefix=web run lint
      - name: 🧹 Run api lint
        run: npm --prefix=api run lint

      - name: 🧪 Run web tests
        run: npm --prefix=web run test
      - name: 🧪 Run API tests
        run: npm --prefix=api run test

      - name: 📦 Build project for feature tests
        run: npm --prefix=web run build --if-present && npm --prefix=api run install-dynamo-local
        env:
          API_BASE_URL: http://localhost:5000/dev
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
          AIRTABLE_BASE_ID: ${{ secrets.AIRTABLE_BASE_ID }}

      - name: 🧪 Run e2e cypress tests
        uses: cypress-io/github-action@v2
        with:
          working-directory: web
          start: npm start, npm --prefix=../api start
          wait-on: 'http://localhost:3000, http://localhost:5000/dev/health'
          record: true
        env:
          CYPRESS_API_BASE_URL: http://localhost:5000/dev
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          CYPRESS_TEST_USER_EMAIL: ${{ secrets.CYPRESS_TEST_USER_EMAIL }}
          CYPRESS_TEST_USER_PASSWORD: ${{ secrets.CYPRESS_TEST_USER_PASSWORD }}
          CYPRESS_AWS_COGNITO_IDENTITY_POOL_ID: ${{ secrets.CYPRESS_AWS_COGNITO_IDENTITY_POOL_ID }}
          CYPRESS_AWS_USER_POOLS_ID: ${{ secrets.CYPRESS_AWS_USER_POOLS_ID }}
          CYPRESS_AWS_USER_POOLS_WEB_CLIENT_ID: ${{ secrets.CYPRESS_AWS_USER_POOLS_WEB_CLIENT_ID }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 📦 Publish source-code artifact
        uses: actions/upload-artifact@v2
        with:
          name: source-${{ github.sha }}
          path: ./source-${{ github.sha }}.tar

  deploy-dev:
    runs-on: ubuntu-latest
    needs: build-and-test
    environment:
      name: dev
    steps:
      - name: 📦 Download source package
        uses: actions/download-artifact@v2
        with:
          name: source-${{ github.sha }}
          path: ${{ github.workspace }}

      - name: 📦 Untar source package
        run: tar -xvf source-${{ github.sha }}.tar

      - name: 🔧 Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: 🔧 Configure Amplify
        uses: ambientlight/amplify-cli-action@0.2.1
        with:
          amplify_command: configure
          amplify_env: dev
          amplify_cli_version: "4.41.2"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1

      - name: 🧰 Install Serverless Framework
        run: npm install -g serverless

      - name: 🔧 Serverless Authentication
        run: sls config credentials --provider aws --key ${{secrets.AWS_ACCESS_KEY_ID}} --secret ${{secrets.AWS_SECRET_ACCESS_KEY}}

      - name: 🧰 Install web dependencies
        run: npm --prefix=web install
      - name: 🧰 Install api dependencies
        run: npm --prefix=api install

      - name: 🚀 Deploy web to AWS Amplify
        uses: ambientlight/amplify-cli-action@0.2.1
        with:
          amplify_command: publish
          amplify_env: dev
          amplify_cli_version: "4.41.2"
        env:
          API_BASE_URL: ${{ secrets.API_BASE_URL_AWS_DEV }}
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
          AIRTABLE_BASE_ID: ${{ secrets.AIRTABLE_BASE_ID }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1

      - name: 🚀 Deploy api with serverless
        run: serverless deploy --verbose --stage dev --region us-east-1
        working-directory: ./api
        env:
          STAGE: dev

  deploy-staging:
    runs-on: ubuntu-latest
    needs: deploy-dev
    environment:
      name: staging
    steps:
      - name: 📦 Download source package
        uses: actions/download-artifact@v2
        with:
          name: source-${{ github.sha }}
          path: ${{ github.workspace }}

      - name: 📦 Untar source package
        run: tar -xvf source-${{ github.sha }}.tar

      - name: 🔧 Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: 🔧 Configure Amplify
        uses: ambientlight/amplify-cli-action@0.2.1
        with:
          amplify_command: configure
          amplify_env: staging
          amplify_cli_version: "4.41.2"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1

      - name: 🧰 Install Serverless Framework
        run: npm install -g serverless

      - name: 🔧 Serverless Authentication
        run: sls config credentials --provider aws --key ${{secrets.AWS_ACCESS_KEY_ID}} --secret ${{secrets.AWS_SECRET_ACCESS_KEY}}

      - name: 🧰 Install web dependencies
        run: npm --prefix=web install
      - name: 🧰 Install api dependencies
        run: npm --prefix=api install

      - name: 🚀 Deploy web to AWS Amplify
        uses: ambientlight/amplify-cli-action@0.2.1
        with:
          amplify_command: publish
          amplify_env: staging
          amplify_cli_version: "4.41.2"
        env:
          API_BASE_URL: ${{ secrets.API_BASE_URL_AWS_STAGING }}
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
          AIRTABLE_BASE_ID: ${{ secrets.AIRTABLE_BASE_ID }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1

      - name: 🚀 Deploy api with serverless
        run: serverless deploy --verbose --stage staging --region us-east-1
        working-directory: ./api
        env:
          STAGE: staging